version: '3.8'
services:
  info-sec-api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017